<a href="https://colab.research.google.com/github/Slamm-alt/2318076_Islam_DataCleansingCafe/blob/main/2318076DataCleansing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



# **1. Import Libraries**

In [1]:
import pandas as pd

In [2]:
# Langkah 1: Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# **2. Baca Dataset Cafe yang kotor**

In [4]:
# Baca file .csv
file_path = '/content/drive/MyDrive/Colab Notebooks/DatasetCafe/dirty_cafe_sales.csv'
data = pd.read_csv(file_path)  # Gunakan read_csv untuk file .csv

In [24]:
# Tampilkan data
print(data)

     Transaction ID      Item Quantity Price Per Unit Total Spent  \
0       TXN_1961373    Coffee        2            2.0         4.0
1       TXN_4977031      Cake        4            3.0        12.0
2       TXN_4271903    Cookie        4            1.0       ERROR
3       TXN_7034554     Salad        2            5.0        10.0
4       TXN_3160411    Coffee        2            2.0         4.0
...             ...       ...      ...            ...         ...
9995    TXN_7672686    Coffee        2            2.0         4.0
9996    TXN_9659401       NaN        3            NaN         3.0
9997    TXN_5255387    Coffee        4            2.0         8.0
9998    TXN_7695629    Cookie        3            NaN         3.0
9999    TXN_6170729  Sandwich        3            4.0        12.0

      Payment Method  Location Transaction Date
0        Credit Card  Takeaway       2023-09-08
1               Cash  In-store       2023-05-16
2        Credit Card  In-store       2023-07-19
3            UNKNOWN   UNKNOWN       2023-04-27
4     Digital Wallet  In-store       2023-06-11
...              ...       ...              ...
9995             NaN   UNKNOWN       2023-08-30
9996  Digital Wallet       NaN       2023-06-02
9997  Digital Wallet       NaN       2023-03-02
9998  Digital Wallet       NaN       2023-12-02
9999            Cash  In-store       2023-11-07

[10000 rows x 8 columns]

# **3. Menampilkan struktur variable data Cafe**

In [39]:
print("Struktur Data Cafe:")
print(data.info())

Struktur Data Cafe:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       10000 non-null  float64
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: float64(1), object(7)
memory usage: 625.1+ KB
None

In [6]:
# Tampilkan nama kolom dan tipe data kolom
column_types = data.dtypes
print(column_types)

Transaction ID      object
Item                object
Quantity            object
Price Per Unit      object
Total Spent         object
Payment Method      object
Location            object
Transaction Date    object
dtype: object

# **4. Data Cleansing-Standarisasi kolom Kode Cafe**

Algoritma yang akan digunakan:
1. Cek apakah kode pelanggan memiliki format "TXN-" di awal.
2. Cek jumlah digit setelah "TXN-". Jika hanya terdapat 4 digit, tambahkan satu
   digit nol di depan sehingga menjadi 7 digit.
3. Tampilkan hasil yang sudah diperbaiki.

In [25]:
# Function to format 'Transaction ID'
def format_transaction_id(transaction_id):
    if isinstance(transaction_id, str):
        if transaction_id.startswith("TXN_"):
            angka = transaction_id.split('_')[-1]
            if angka.isdigit():
                return "TXN_" + angka.zfill(7)
    return transaction_id

In [26]:
# Apply the function to the 'Transaction ID' column
data['Transaction ID'] = data['Transaction ID'].apply(format_transaction_id)

In [28]:
# Display the updated 'Transaction ID' column
data[['Transaction ID']].head()

  Transaction ID
0    TXN_1961373
1    TXN_4977031
2    TXN_4271903
3    TXN_7034554
4    TXN_3160411

Kolom Kode Transaction telah diperbaiki. Tidak ada kode pelanggan dengan 4 digit yang perlu ditambahkan angka nol, karena semua sudah memiliki 7 digit setelah "TXN-".

# **5. Data Cleansing-Standarisasi kolom Transaction ID**

In [30]:
import pandas as pd
import re

# Baca file .csv
file_path = '/content/drive/MyDrive/Colab Notebooks/DatasetCafe/dirty_cafe_sales.csv'
df = pd.read_csv(file_path)

# Define a function to clean the 'Transaction ID' column
def clean_transaction_id(transaction_id):
    # Define patterns to remove
    patterns = [
        r'\s+',          # Menghapus spasi
        r'[^A-Z0-9_]',   # Menghapus karakter selain huruf, angka, dan _
    ]

    # Compile the patterns into a single regex pattern
    combined_pattern = re.compile('|'.join(patterns), flags=re.IGNORECASE)

    # Remove the patterns
    cleaned_transaction_id = combined_pattern.sub('', str(transaction_id)).strip().upper()

    return cleaned_transaction_id

# Apply the cleaning function to the 'Transaction ID' column
df['Transaction ID Bersih'] = df['Transaction ID'].apply(clean_transaction_id)

# Display the cleaned DataFrame
df[['Transaction ID', 'Transaction ID Bersih']].head()

  Transaction ID Transaction ID Bersih
0    TXN_1961373           TXN_1961373
1    TXN_4977031           TXN_4977031
2    TXN_4271903           TXN_4271903
3    TXN_7034554           TXN_7034554
4    TXN_3160411           TXN_3160411

# **6. Data Cleansing-Standarisasi kolom Transaction Date**

In [32]:
# Define a function to standardize the date format
def standardize_date(date):
    try:
        # Convert the date to datetime format and then to the desired format
        standardized_date = pd.to_datetime(date, errors='coerce').strftime('%d-%m-%Y')
    except:
        standardized_date = None
    return standardized_date

# Apply the standardization function to the 'Transaction Date' column
df['Transaction Date Standar'] = df['Transaction Date'].apply(standardize_date)

# Display the DataFrame with the standardized dates
df[['Transaction Date', 'Transaction Date Standar']].head()

  Transaction Date Transaction Date Standar
0       2023-09-08               08-09-2023
1       2023-05-16               16-05-2023
2       2023-07-19               19-07-2023
3       2023-04-27               27-04-2023
4       2023-06-11               11-06-2023

# **7. Data Cleansing-Deduplikasi Data**

Menampilkan data yang sama dalam semua kolom

In [33]:
# Find duplicate rows based on columns 'Item', 'Quantity', 'Price Per Unit',
# 'Total Spent', 'Payment Method', 'Location', and 'Transaction Date'
duplicate_rows = df[df.duplicated([
    'Item',
    'Quantity',
    'Price Per Unit',
    'Total Spent',
    'Payment Method',
    'Location',
    'Transaction Date'
], keep=False)]

# Display the duplicate rows
duplicate_rows

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Transaction ID Bersih,Transaction Date Standar
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31,TXN_2602893,31-03-2023
27,TXN_5695074,Juice,4,3.0,12.0,Credit Card,Takeaway,2023-04-10,TXN_5695074,10-04-2023
115,TXN_1001832,Salad,2,5.0,10.0,Cash,Takeaway,UNKNOWN,TXN_1001832,None
126,TXN_9646452,Juice,5,3.0,15.0,Credit Card,NaN,2023-09-16,TXN_9646452,16-09-2023
300,TXN_1623966,Tea,2,1.5,3.0,Cash,Takeaway,UNKNOWN,TXN_1623966,None
...,...,...,...,...,...,...,...,...,...,...
9898,TXN_8999360,Juice,3,3.0,9.0,Cash,Takeaway,2023-09-27,TXN_8999360,27-09-2023
9909,TXN_2112522,Sandwich,5,4.0,20.0,Digital Wallet,Takeaway,2023-04-30,TXN_2112522,30-04-2023
9930,TXN_4428252,Sandwich,3,4.0,12.0,NaN,Takeaway,2023-10-31,TXN_4428252,31-10-2023
9967,TXN_8563793,Juice,4,3.0,12.0,NaN,In-store,2023-03-26,TXN_8563793,26-03-2023
9989,TXN_1741685,Juice,5,3.0,15.0,Cash,NaN,2023-08-18,TXN_1741685,18-08-2023

Data duplikat berdasarkan semua kolom

In [34]:
# Sort the dataframe by 'Transaction ID' to ensure that the smallest Transaction ID is kept
df_sorted = df.sort_values(by='Transaction ID')

# Drop duplicates based on the transaction details, keeping the first (smallest Transaction ID)
df_deduplicated = df_sorted.drop_duplicates(
    subset=[
        'Item',
        'Quantity',
        'Price Per Unit',
        'Total Spent',
        'Payment Method',
        'Location',
        'Transaction Date'
    ],
    keep='first'
)

# Display the resulting dataframe
df_deduplicated.reset_index(drop=True, inplace=True)
df_deduplicated.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Transaction ID Bersih,Transaction Date Standar
0,TXN_1000555,Tea,1,1.5,1.5,Credit Card,In-store,2023-10-19,TXN_1000555,19-10-2023
1,TXN_1001832,Salad,2,5.0,10.0,Cash,Takeaway,UNKNOWN,TXN_1001832,None
2,TXN_1002457,Cookie,5,1.0,5.0,Digital Wallet,Takeaway,2023-09-29,TXN_1002457,29-09-2023
3,TXN_1003246,Juice,2,3.0,6.0,NaN,NaN,2023-02-15,TXN_1003246,15-02-2023
4,TXN_1004184,Smoothie,1,4.0,4.0,Credit Card,In-store,2023-05-18,TXN_1004184,18-05-2023

# **8. Data Enrichment**

In [35]:
# Count the missing values in the 'Total Spent' column
missing_values_count = df['Total Spent'].isna().sum()
missing_values_count

np.int64(173)

In [40]:
# Ubah kolom 'Total Spent' menjadi tipe numerik terlebih dahulu, ubah nilai non-angka (seperti 'ERROR') menjadi NaN
data['Total Spent'] = pd.to_numeric(data['Total Spent'], errors='coerce')

# Menghitung rata-rata dari kolom 'Total Spent', abaikan nilai yang hilang (NA)
mean_value = data['Total Spent'].mean()

# Mengisi nilai yang hilang dengan langsung menetapkan hasilnya ke kolom (menghindari FutureWarning)
data['Total Spent'] = data['Total Spent'].fillna(mean_value)

# Tampilkan beberapa baris pertama untuk memastikan hasilnya
data[['Total Spent']].head()

   Total Spent
0     4.000000
1    12.000000
2     8.924352
3    10.000000
4     4.000000